### PR TITLE
Shield

### PR DESCRIPTION
**Pull request by chern042**
Made a fully functional shield bar.

### CODE REVIEW

**Comment by RossBaumgartner** [comment]
sheild function needs to be called by the card so that it can be used in game and tested

**Comment by SebastienGorman** [comment]
Resolves #202 
Resolves #178 
Resolves #193 
Resolves #179

**Review by SebastienGorman — APPROVED** [review]
Made last changes myself, so someone else should also review before merging please

**Review by RossBaumgartner — APPROVED** [review]
now working as intended and building

**Pull request merged**
