### PR TITLE
Transferred every change from master and seb-chest-2 in this branch

### PR DESCRIPTION
**Pull request by SebastienGorman**
It might be easier for you to go through the commits in the seb-chest-2 branch to see the progression of the inventory system. This branch had to be made to manually transfer the changes to the SampleScene.unity file without breaking anything in master since we are missing a reliable merging tool for this type of file (coming very soon).

### CODE REVIEW

**Comment by SebastienGorman** [comment]
Keybings : 
E to open pouch when in range
P to spawn a health potion in your inventory

**Comment by AndreiBaetica** [comment]
> Keybings :
> E to open pouch when in range
> P to spawn a health potion in your inventory

We should change P to something before we merge, it doubles up as the grid toggle.

**Comment by RossBaumgartner** [comment]
-bag menu is open when the game starts, it should start off closed
-rebind potion button or grid button so that there is no keybind overlap for testing
-bag menu location is strange (look in slack pr channel thread for example)
-can we also have a key binding to open the bag?

other than those bugs everything works great, code looks good

**Review by RossBaumgartner — APPROVED** [review]
my comments have been addressed, approved

**Review by AndreiBaetica — APPROVED** [review]

**Pull request merged**
