### PR TITLE
added merchant NPC

### PR DESCRIPTION
**Pull request by AndreiBaetica**
roses are red
violets are blue
I'm bad at poetry
the animation UI makes me cry

### CODE REVIEW

**Comment by RossBaumgartner** [comment]
is he supposed to be animated in game? he is just static in game for me

**Comment by AndreiBaetica** [comment]
> is he supposed to be animated in game? he is just static in game for me

Yeah, supposed to have an idle anim. If you launch sample scene directly is he still static?

**Comment by RossBaumgartner** [comment]
> > is he supposed to be animated in game? he is just static in game for me
> 
> Yeah, supposed to have an idle anim. If you launch sample scene directly is he still static?

Yea still static just loading the sample scene

**Review by RossBaumgartner — APPROVED** [review]
he is now animated ✔

**Review by SebastienGorman — APPROVED** [review]

**Pull request merged**
